trigger:
  branches:
    include:  
    - main
  paths:
    include:
    - admin

pool:
  name: 'Default'

resources:
  repositories:
  - repository: templates
    type: git
    name: DevopsTools/prodest-build-deploy-templates

jobs:
- template: buildDeployDocsV2.yml@templates
  parameters:
    environment: IISProducao
    sistema: docs.admin.acessocidadao
    orgao: Prodest
    docsPath: admin
    hostnamesuffix: .es.gov.br
